name: Run action on commit

on:
  push:
    branches:
      - master

jobs:
  run-on-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Create zip archive
        run: zip -r veracode-artifact.zip . -x .git/**\* bin/**\* e2e/**\* tests/**\* node_modules/**\* *.pyd *.mwb *.exe *.dll *.bin *.png *.xml *.bat *.g2p *.gp4 *.wav *.jpg *.svg *.sfx *.prx *.sb *.nrm *.config *.ini *.pdf *.dat *.docx *.whl *.so *_arm64 *_armhf *_x64 *.xlsm *.sql
      
      - name: Move artifact to upload folder
        run: |
          mkdir -p veracode-upload
          mv veracode-artifact.zip veracode-upload/
      
      - name: Verify artifact
        run: |
          ls -lh veracode-upload
          file veracode-upload/veracode-artifact.zip
          
      - name: Policy Scan
        uses: veracode/uploadandscan-action@main-proxy
        id: upload_and_scan
        with:
          appname: "action-test-proxyQF-v4/example-javascript"
          createprofile: true
          policy: ""
          version: 28145163250-6
          filepath: "veracode-upload/veracode-artifact.zip"
          # filepath: "veracode-upload"
          # include: "veracode-artifact.zip"
          vid: 'e766657eb8a4ac4f026453d46358443a'
          vkey: '0e000c7b35a7e1ef45ea4e3dad071d0fb9c0df54c08641e9588623e238923ff957816cb5bc5e06bc7a18e506db25fc96271eba4af97ed17accbb5e6d941f12d2'
          scantimeout: 1
          failbuild: false
          deleteincompletescan: true
          debug: false
          createsandbox: false
